### ISSUE TITLE
Improve branch merging message when there is a problem

### ISSUE THREAD

**Issue by nicoddemus** [ESSS/err-stash#17]
Currently if there are any problems with a merge, the bot replies with:

![Clipboard - April 11, 2019 7_54 AM](https://user-images.githubusercontent.com/1085180/55955265-588b6d80-5c37-11e9-9c0b-75a406b72fa1.png)

What happens is that we use the Stash API to check if a branch is mergeable, and if the API replies that it is not, the bot assumes the cause is a conflict. 

What happens is that a branch might not be mergeable by a number of reasons: conflicts are a common one, but we also can configure a repository to block merges without X approvals, unless all builds are passing, among others.

We should improve the message: check if we can obtain the actual reason from the API, and if not, just say it is not mergeable and suggest that the user go to the PR to see the reason.

Relevant code:

https://github.com/ESSS/err-stash/blob/10ea2e49343e29f825729329abdff06d9140de38/err_stash.py#L223-L233

**Comment by tadeu** [comment]
Relevant API documentation: https://docs.atlassian.com/DAC/rest/stash/3.0.1/stash-rest.html#idp1001504

This part is funny:

![image](https://user-images.githubusercontent.com/955251/55957250-3516f180-5c3c-11e9-8d62-3e338428161a.png)

**Comment by nicoddemus** [comment]
Great, thanks @tadeu!

So we seem to be able to list the `vetoes` then. I'm sure GitHub supports something similar.

**Comment by gcardozo123** [comment]
Solved during pull request #22
