### ISSUE TITLE
Wrong github url for creating new PR

### ISSUE THREAD

**Issue by haensch-mauricio** [ESSS/err-stash#24]
After trying a merge that is missing PRs from other branches, the suggested url for creating a PR in github projects is wrong:

```
These repositories have commits in `fb-ASIM-606-merge-with-master` but no PRs:
`eden`: *2 commits* (create PR)
`etk`: *6 commits* (create PR)
`alfasim-sdk`: *2 commits* (create PR)
You need to create PRs for your changes before merging this branch.
```

Where `alfasim-sdk` is a github project but the generated link in (create PR) is following stash pattern for creating PRs: `https://github.com/projects/ESSS/repos/alfasim-sdk/compare/commits?sourceBranch=fb-ASIM-606-merge-with-master&targetBranch=refs%2Fheads%2Ffb-ASIM-606-well-editor` (where the expected url should be `https://github.com/ESSS/alfasim-sdk/compare/fb-ASIM-606-merge-with-master`).

**Comment by gcardozo123** [comment]
Oh, I see. `GithubAPI` `url` is `"https://github.com"` but this [line](https://github.com/ESSS/err-stash/blob/5be6fc12387ca1ec4e292786a29429e53b198cf8/err_stash.py#L390) checks `if "github.com/" in url:`, that `/` should'nt be there.

Thanks for reporting!
